// Mizan — Drizzle schema (Neon Postgres).
//
// This is the typed query surface for the app. The authoritative DDL —
// including CHECK constraints, indexes, and the two integrity triggers
// (updated_at + the deferred debit=credit balance check) — lives in
// db/NEON_SETUP.sql and is applied to Neon directly. Keep the two in sync.
//
// Auth note: we moved off Supabase Auth to Clerk, so any id that used to be a
// Postgres `uuid` referencing auth.users is now `text` holding the Clerk user
// id (profiles.id and every *_by / owner_id / user_id that points at a person).
// Company/document/ledger ids stay uuid (generated by the DB).

import {
  pgTable,
  text,
  uuid,
  timestamp,
  numeric,
  integer,
  bigint,
  boolean,
  date,
  jsonb,
} from "drizzle-orm/pg-core";

const createdAt = () =>
  timestamp("created_at", { withTimezone: true }).notNull().defaultNow();

// ── people & tenancy ────────────────────────────────────────────────────────

export const waitlist = pgTable("waitlist", {
  id: bigint("id", { mode: "number" }).primaryKey().generatedAlwaysAsIdentity(),
  email: text("email").notNull(),
  company: text("company"),
  stage: text("stage"),
  createdAt: createdAt(),
});

// Clerk owns the user record; profiles.id is the Clerk user id (e.g. "user_...").
export const profiles = pgTable("profiles", {
  id: text("id").primaryKey(),
  fullName: text("full_name"),
  role: text("role").notNull().default("client"), // client | admin
  createdAt: createdAt(),
});

export const companies = pgTable("companies", {
  id: uuid("id").primaryKey().defaultRandom(),
  ownerId: text("owner_id").notNull(),
  name: text("name").notNull(),
  freeZone: text("free_zone"),
  licenseNo: text("license_no"),
  trn: text("trn"),
  plan: text("plan").notNull().default("starter"), // starter | growth | pro
  status: text("status").notNull().default("onboarding"), // onboarding | active | paused
  region: text("region").notNull().default("ae"), // ae | gb
  vatRegistered: boolean("vat_registered").notNull().default(true),
  invoiceCounter: integer("invoice_counter").notNull().default(0),
  createdAt: createdAt(),
});

export const companyMembers = pgTable("company_members", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull(),
  userId: text("user_id"), // null until the invited person signs in
  invitedEmail: text("invited_email").notNull(),
  role: text("role").notNull().default("tax_agent"), // owner|accountant|tax_agent|viewer
  status: text("status").notNull().default("pending"), // pending|active|revoked
  invitedBy: text("invited_by"),
  createdAt: createdAt(),
});

// ── documents & compliance ──────────────────────────────────────────────────

export const documents = pgTable("documents", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull(),
  uploadedBy: text("uploaded_by").notNull(),
  storagePath: text("storage_path").notNull(), // R2 object key
  originalName: text("original_name").notNull(),
  kind: text("kind").notNull().default("other"), // invoice|receipt|bank_statement|other
  status: text("status").notNull().default("new"), // new|reading|processed|failed
  createdAt: createdAt(),
});

export const complianceItems = pgTable("compliance_items", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull(),
  kind: text("kind").notNull(),
  title: text("title").notNull(),
  dueDate: date("due_date"),
  status: text("status").notNull().default("upcoming"),
  filedAt: timestamp("filed_at", { withTimezone: true }),
  notes: text("notes"),
  createdAt: createdAt(),
});

export const messages = pgTable("messages", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull(),
  senderId: text("sender_id").notNull(),
  body: text("body").notNull(),
  createdAt: createdAt(),
});

// ── bank import / rules engine (older "transactions" books) ──────────────────

export const statementImports = pgTable("statement_imports", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull(),
  uploadedBy: text("uploaded_by").notNull(),
  sourceName: text("source_name").notNull(),
  sourcePath: text("source_path"),
  periodLabel: text("period_label"),
  rowCount: integer("row_count").notNull().default(0),
  postedCount: integer("posted_count").notNull().default(0),
  reviewCount: integer("review_count").notNull().default(0),
  status: text("status").notNull().default("committed"), // parsed|committed
  createdAt: createdAt(),
});

export const transactions = pgTable("transactions", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull(),
  importId: uuid("import_id"),
  txnDate: date("txn_date").notNull(),
  description: text("description").notNull(),
  counterparty: text("counterparty"),
  amount: numeric("amount", { precision: 14, scale: 2 }).notNull(),
  direction: text("direction").notNull(), // in | out
  accountCode: text("account_code"),
  category: text("category"),
  vatRate: numeric("vat_rate", { precision: 5, scale: 4 }).notNull().default("0"),
  vatAmount: numeric("vat_amount", { precision: 14, scale: 2 }).notNull().default("0"),
  netAmount: numeric("net_amount", { precision: 14, scale: 2 }).notNull().default("0"),
  status: text("status").notNull().default("review"), // posted|review|uncategorized
  confidence: numeric("confidence", { precision: 4, scale: 3 }),
  source: text("source").notNull().default("manual"), // rule|ai|manual|import|seed
  reason: text("reason"),
  createdBy: text("created_by"),
  createdAt: createdAt(),
  postedAt: timestamp("posted_at", { withTimezone: true }),
});

export const vendorRules = pgTable("vendor_rules", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull(),
  matchText: text("match_text").notNull(),
  accountCode: text("account_code").notNull(),
  category: text("category").notNull(),
  vatRate: numeric("vat_rate", { precision: 5, scale: 4 }).notNull().default("0"),
  direction: text("direction"),
  hits: integer("hits").notNull().default(0),
  createdBy: text("created_by"),
  createdAt: createdAt(),
});

export const taxPacks = pgTable("tax_packs", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull(),
  periodLabel: text("period_label").notNull(),
  periodStart: date("period_start"),
  periodEnd: date("period_end"),
  storagePath: text("storage_path"),
  recipientEmail: text("recipient_email"),
  totals: jsonb("totals"),
  status: text("status").notNull().default("draft"), // draft|shared|sent
  createdBy: text("created_by"),
  createdAt: createdAt(),
});

// ── AI ledger + double-entry engine ─────────────────────────────────────────

export const ledgerEntries = pgTable("ledger_entries", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull(),
  documentId: uuid("document_id"),
  entryDate: date("entry_date"),
  description: text("description").notNull().default(""),
  counterparty: text("counterparty"),
  category: text("category").notNull().default("uncategorised"),
  direction: text("direction").notNull().default("expense"), // income | expense
  currency: text("currency").notNull().default("AED"),
  amount: numeric("amount", { precision: 14, scale: 2 }).notNull().default("0"),
  vatAmount: numeric("vat_amount", { precision: 14, scale: 2 }).notNull().default("0"),
  confidence: numeric("confidence", { precision: 4, scale: 3 }),
  source: text("source").notNull().default("ai"), // ai | manual
  status: text("status").notNull().default("draft"), // draft|reviewed|approved
  notes: text("notes"),
  reviewedBy: text("reviewed_by"),
  reversalOf: uuid("reversal_of"), // set on a reversing line → the original id
  reversedAt: timestamp("reversed_at", { withTimezone: true }), // set on a reversed original
  createdAt: createdAt(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const accounts = pgTable("accounts", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull(),
  code: text("code").notNull(),
  name: text("name").notNull(),
  type: text("type").notNull(), // asset|liability|equity|income|expense
  vatTreatment: text("vat_treatment").notNull().default("none"), // none|input|output
  createdAt: createdAt(),
});

export const journalEntries = pgTable("journal_entries", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull(),
  ledgerEntryId: uuid("ledger_entry_id"), // unique; null for manual journals
  entryDate: date("entry_date").notNull(),
  memo: text("memo").notNull().default(""),
  source: text("source").notNull().default("ledger"), // ledger|manual|adjustment
  createdAt: createdAt(),
});

export const journalLines = pgTable("journal_lines", {
  id: uuid("id").primaryKey().defaultRandom(),
  entryId: uuid("entry_id").notNull(),
  accountId: uuid("account_id").notNull(),
  debit: numeric("debit", { precision: 14, scale: 2 }).notNull().default("0"),
  credit: numeric("credit", { precision: 14, scale: 2 }).notNull().default("0"),
});

export const bankTransactions = pgTable("bank_transactions", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull(),
  txnDate: date("txn_date").notNull(),
  description: text("description").notNull().default(""),
  amount: numeric("amount", { precision: 14, scale: 2 }).notNull(), // signed
  currency: text("currency").notNull().default("AED"),
  matchedEntryId: uuid("matched_entry_id"),
  status: text("status").notNull().default("unmatched"), // unmatched|matched|ignored
  createdAt: createdAt(),
});

export const accountingPeriods = pgTable("accounting_periods", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull(),
  label: text("label").notNull(),
  startDate: date("start_date").notNull(),
  endDate: date("end_date").notNull(),
  status: text("status").notNull().default("open"), // open | closed
  vatOutput: numeric("vat_output", { precision: 14, scale: 2 }).notNull().default("0"),
  vatInput: numeric("vat_input", { precision: 14, scale: 2 }).notNull().default("0"),
  vatNet: numeric("vat_net", { precision: 14, scale: 2 }).notNull().default("0"),
  taxableProfit: numeric("taxable_profit", { precision: 14, scale: 2 }).notNull().default("0"),
  corporateTax: numeric("corporate_tax", { precision: 14, scale: 2 }).notNull().default("0"),
  closedAt: timestamp("closed_at", { withTimezone: true }),
  createdAt: createdAt(),
});

// ── customers & invoicing ───────────────────────────────────────────────────

export const customers = pgTable("customers", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull(),
  name: text("name").notNull(),
  email: text("email"),
  phone: text("phone"),
  trn: text("trn"),
  address: text("address"),
  notes: text("notes"),
  archived: boolean("archived").notNull().default(false),
  createdBy: text("created_by"),
  createdAt: createdAt(),
});

export const invoices = pgTable("invoices", {
  id: uuid("id").primaryKey().defaultRandom(),
  companyId: uuid("company_id").notNull(),
  customerId: uuid("customer_id").notNull(),
  number: text("number").notNull(),
  seq: integer("seq").notNull(),
  issueDate: date("issue_date").notNull().defaultNow(),
  dueDate: date("due_date"),
  currency: text("currency").notNull().default("AED"),
  status: text("status").notNull().default("draft"), // draft|sent|paid|void
  subtotal: numeric("subtotal", { precision: 14, scale: 2 }).notNull().default("0"),
  vatAmount: numeric("vat_amount", { precision: 14, scale: 2 }).notNull().default("0"),
  total: numeric("total", { precision: 14, scale: 2 }).notNull().default("0"),
  notes: text("notes"),
  shareToken: text("share_token").unique(),
  sentAt: timestamp("sent_at", { withTimezone: true }),
  paidAt: timestamp("paid_at", { withTimezone: true }),
  ledgerEntryId: uuid("ledger_entry_id"),
  paymentLink: text("payment_link"),
  placeOfSupply: text("place_of_supply"),
  einvoice: jsonb("einvoice"),
  createdBy: text("created_by"),
  createdAt: createdAt(),
});

export const invoiceLines = pgTable("invoice_lines", {
  id: uuid("id").primaryKey().defaultRandom(),
  invoiceId: uuid("invoice_id").notNull(),
  companyId: uuid("company_id").notNull(),
  position: integer("position").notNull().default(0),
  description: text("description").notNull(),
  qty: numeric("qty", { precision: 12, scale: 3 }).notNull().default("1"),
  unitPrice: numeric("unit_price", { precision: 14, scale: 2 }).notNull().default("0"),
  vatRate: numeric("vat_rate", { precision: 5, scale: 4 }).notNull().default("0"),
  lineNet: numeric("line_net", { precision: 14, scale: 2 }).notNull().default("0"),
  lineVat: numeric("line_vat", { precision: 14, scale: 2 }).notNull().default("0"),
  lineTotal: numeric("line_total", { precision: 14, scale: 2 }).notNull().default("0"),
});

// Convenience row types
export type Profile = typeof profiles.$inferSelect;
export type Company = typeof companies.$inferSelect;
export type Document = typeof documents.$inferSelect;
export type LedgerEntry = typeof ledgerEntries.$inferSelect;
export type Transaction = typeof transactions.$inferSelect;
export type Invoice = typeof invoices.$inferSelect;
export type InvoiceLine = typeof invoiceLines.$inferSelect;
export type Customer = typeof customers.$inferSelect;
