import { redirect } from "next/navigation";
import { getActiveCompany } from "@/lib/books/repo";
import { loadSummary } from "@/lib/books/summary";
import { money, longDate } from "@/lib/demo/format";
import { REGIONS } from "@/lib/demo/regions";

export const metadata = { title: "Accounts pack — print", robots: { index: false, follow: false } };

// Print-optimised report. The user prints to PDF from the browser.
export default async function PrintReport() {
  const company = await getActiveCompany();
  if (!company) redirect("/app/onboarding");

  const { reports } = await loadSummary(company);
  const cfg = REGIONS[company.region];
  const period =
    reports.periodStart && reports.periodEnd
      ? `${longDate(reports.periodStart, company.region)} – ${longDate(reports.periodEnd, company.region)}`
      : "—";

  return (
    <div className="mx-auto max-w-3xl bg-paper p-10 text-ink print:p-0">
      <p className="text-xs text-ink-soft print:hidden">
        Use your browser&apos;s <span className="font-medium">Print → Save as PDF</span> to export this pack.
      </p>

      <header className="mt-4 flex items-end justify-between border-b-2 border-ink/20 pb-4">
        <div>
          <h1 className="font-display text-2xl font-semibold">{company.name}</h1>
          <p className="text-sm text-ink-soft">{cfg.label} · {cfg.filingAuthority}</p>
          <p className="text-sm text-ink-soft">{period}</p>
        </div>
        <p className="font-display text-lg font-semibold">Mizan</p>
      </header>

      <section className="mt-8">
        <h2 className="font-display text-lg font-semibold">Profit &amp; loss</h2>
        <p className="mt-3 text-xs font-semibold uppercase tracking-wide text-ink-soft">Income</p>
        {reports.incomeLines.map((l) => (
          <Row key={l.code} a={l.name} b={money(l.amount, company.region)} />
        ))}
        <Row a="Total revenue" b={money(reports.revenue, company.region)} strong />
        <p className="mt-4 text-xs font-semibold uppercase tracking-wide text-ink-soft">Expenses</p>
        {reports.expenseLines.map((l) => (
          <Row key={l.code} a={l.name} b={`−${money(l.amount, company.region)}`} />
        ))}
        <Row a="Total expenses" b={`−${money(reports.totalExpenses, company.region)}`} strong />
        <div className="mt-3 flex justify-between border-t-2 border-ink/20 pt-3">
          <span className="font-display text-base font-semibold">Net profit</span>
          <span className="tnum font-display text-base font-semibold">{money(reports.netProfit, company.region)}</span>
        </div>
      </section>

      <section className="mt-8 grid grid-cols-2 gap-8">
        <div>
          <h2 className="font-display text-lg font-semibold">{cfg.vatReturnName}</h2>
          <Row a="Output VAT" b={money(reports.outputVat, company.region)} />
          <Row a="Input VAT" b={`−${money(reports.inputVat, company.region)}`} />
          <Row a="Net VAT due" b={money(reports.vatDue, company.region)} strong />
        </div>
        <div>
          <h2 className="font-display text-lg font-semibold">{cfg.taxName}</h2>
          <Row a="Projected annual profit" b={money(reports.annualProjectedProfit, company.region)} />
          <Row a="0% band" b={money(cfg.taxFreeThreshold, company.region)} />
          <Row
            a="Estimated tax"
            b={reports.withinFreeBand ? money(0, company.region) : money(reports.taxSetAside, company.region)}
            strong
          />
        </div>
      </section>

      <p className="mt-10 text-xs text-ink-soft">
        Generated by Mizan from {reports.postedCount} posted transactions.
        {reports.reviewCount > 0 && ` ${reports.reviewCount} transaction(s) still in review are excluded.`}
      </p>
    </div>
  );
}

function Row({ a, b, strong }: { a: string; b: string; strong?: boolean }) {
  return (
    <div className={`flex justify-between border-t border-line py-1.5 text-sm ${strong ? "font-semibold" : ""}`}>
      <span className={strong ? "" : "text-ink-soft"}>{a}</span>
      <span className="tnum">{b}</span>
    </div>
  );
}
